mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path("", views.home , name="home"),
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls, name="admin"),
    path("__debug__/", include("debug_toolbar.urls")),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_view, name= "signup"),
    path("users/<username>/", views.profile, name= 'profile'),
    path("accounts/login/", views.login_view, name='accountlogin')
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    # ex;  /polls/
    path("", views.IndexView.as_view(), name="index"),
    #  ex: /polls/5/
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # ex: /polls/5/results
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # ex: /polls/5/vote
    path("<int:question_id>/vote/", views.vote, name="vote"),
    # Contact path below
    path("contact/",views.send_message , name='contact'),
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib import admin

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    @admin.display(
            boolean=True,
            ordering="pub_date",
            description="Published recently?"
    )

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

class Artist(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Album(models.Model):
    title = models.CharField(max_length=100)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
class Song(models.Model):
    title = models.CharField(max_length=100)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

polls/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label="Your Name", max_length=100)

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    name = forms.CharField(max_length=50)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    
    

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from .models import Choice, Question
from django.views import generic
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings
from .forms import ContactForm
import os
from dotenv import load_dotenv
load_dotenv()


# imports for authentication
from django.contrib.auth.forms import  UserCreationForm, AuthenticationForm
from django.contrib.auth.models import  User
from django.contrib.auth import  login , logout, authenticate
from django.contrib.auth.decorators import  login_required
from django.utils.decorators import  method_decorator

recipientAddress = os.getenv('SMTP_EMAIL')
# Create your views here.
# views = routes
# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     context = { "latest_question_list": latest_question_list }
#     return render(request, "polls/index.html", context)

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/detail.html", {"question": question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/results.html", {"question": question})
def send_message(request):
    if request.method =="POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = f"{form.cleaned_data['name']} sent you a message!"
            message = f"Name: {form.cleaned_data['name']}\n\nSubject: {form.cleaned_data['subject']}\n\nSender: {form.cleaned_data['sender']}\n\nMessage:\n{form.cleaned_data['message']}"
            sender = form.cleaned_data['sender']
            send_mail(
                subject, #title
                message,
                sender,
                [recipientAddress],
                fail_silently=False,
            )
            form = ContactForm()
            return HttpResponseRedirect('/polls')
        else:
            form = ContactForm()
            return render(request, "polls/contact.html", { 'form': form })
    else:
        form = ContactForm()
        return render(request, "polls/contact.html", {"form" : form }) 
        #create a form instance and populate it with the data from the request:
        # form = ContactForm(request.post)
    #     if form.is_valid():
    #         #process the data in the form.cleaned_data as required
    #         subject = form.cleaned_data['subject']
    #         message = form.cleaned_data['message']
    #         sender = form.cleaned_data['sender']
    #         cc_myself = form.cleaned_data['cc_myself']

    #         recipients = [recipientAddress]
    #         if cc_myself:
    #             recipients.append(sender)
            
    #         send_mail(subject, message, sender, recipients)
    #         # redirect to a new url
    #         return HttpResponseRedirect('/thanks/')
    # else:
    #     form = ContactForm()

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
        :5
    ]
    
class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))



# from pymongo import MongoClient
# import os
# from dotenv import load_dotenv
# load_dotenv()
# from bson import ObjectId

# client = MongoClient(os.getenv('MONGO_URI'))
# db = client['mysite']
# question = db.polls_question
# print('all collections', db.list_collection_names())
# # db.polls_question.insert_one({
# #     'question_text': 'What is your favorite color?',
# #     'pub_date': datetime.now()
# # })
# print('----Availiable Questions----')
# all_questions = db.polls_question.find()
# q_num = 1
# for q in all_questions:
#     print('Question number '+str(q_num)+': '+q['question_text']+' (Published on: '+str(q['pub_date'])+')')
#     q_num += 1
# print('')

# new_q = {"question_text": "What's new?", "pub_date": datetime.now()}

# does_new_q_exist_in_db = False

# for q in db.polls_question.find():
#     if q['question_text'] == new_q['question_text']:
#         does_new_q_exist_in_db = True
#         break
# if not does_new_q_exist_in_db:
#     db.polls_question.insert_one(new_q)
#     print('New question added to the database!')
# else:
#     print('Question already exists in the database!')
# print('')

# # TODO search by question_text
# qtext_s = question.find_one({ 'question_text' : "What's new?" })
# print('Search by question_text= '+ qtext_s['question_text']+ '(published on: ' +str(qtext_s['pub_date'])+ ')' )
# # TODO Search a question by a certain text
# specific_question = (
#     db.polls_question.find_one({"question_text": {"$regex": "what", "$options": "i"}}),
# )
# print('specific search'+ specific_question[0]['question_text']+ 'published: '+  specific_question[0]['pub_date'])
# # TODO Search all questions by one date
# target_date = datetime(2024, 2, 3)
# found_questions = question.find(
#     {"pub_date": {"$gte": target_date, "$lt": target_date + timedelta(days=1)}}
# )

# # Print or iterate over the found questions
# print("----Find questions with the specified date-----")
# for question in found_questions:
#     print(question)
# # search_date = { 'pub_date': datetime.now() }
# # result = question.find(search_date).sort("pub_date", -1) # sort by pub_date in descending order
# # for q in result:
# #     print('date result', q['question_text'], 'published: ', str(q['pub_date']))
# # TODO Update a question (pub_date -> needs to be set to current date)
# update_data = {
#     "$set": {
#         "question_text": "How are you today?",
#         "pub_date": datetime.now()
#         }
# }
# update_s_data = { '_id':ObjectId('65bea3a2d2cecb793c0a1b0e') }
# db.polls_question.find_one_and_update(update_s_data, update_data)
# update_result = db.polls_question.find_one(update_s_data)
# print('Updated Question= '+ update_result['question_text']+ '(updated on: ' +str(update_result['pub_date'])+ ')' )

# # TODO Delete a question
# # 

polls/templates/polls/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Contact Us</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>

    <!-- Navbar -->
    <div class="w3-top">
        <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
            <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1"
                href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
                <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white w3-mobile">MySite</a>
                <a href="{% url 'polls:index' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white w3-mobile">Polls</a>
                <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white w3-mobile">Logon</a>
                <a href="{% url 'polls:contact' %}" class="w3-bar-item w3-button w3-theme-l1 w3-mobile">Contact</a>
            <!-- <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Clients</a> -->
            <!-- <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Partners</a> -->
        </div>
    </div>

    <div class="w3-row w3-padding-64">
        <div class="w3-twothird w3-container">
            <form  action="{% url 'polls:contact' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Submit">
            </form>
            
        </div>
    </div>

    
    <footer id="myFooter">
        <div class="w3-bottom w3-container w3-theme-l2 w3-padding-32">
            <h4>Footer</h4>
        <div class="w3-container w3-theme-l1">
            <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
        </div>
        </div>

    </footer>

    <!-- END MAIN -->
    <!-- </div> -->
</body>

</html>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
<a href="{% url 'polls:index' %}">View all Questions</a>

polls/templates/polls/form_snippet.html
{% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
{% endfor %}

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Polls</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>

    <!-- Navbar -->
    <div class="w3-top">
        <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
            <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1"
                href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
                <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white w3-mobile">MySite</a>
                <a href="{% url 'polls:index' %}" class="w3-bar-item w3-button w3-theme-l1 w3-mobile">Polls</a>
                <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white w3-mobile">Logon</a>
                <a href="{% url 'polls:contact' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white w3-mobile">Contact</a>
            <!-- <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Clients</a> -->
            <!-- <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Partners</a> -->
        </div>
    </div>

    <!-- Sidebar -->
    <!-- <nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
        <a href="javascript:void(0)" onclick="w3_close()"
            class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
            <i class="fa fa-remove"></i>
        </a>
        <h4 class="w3-bar-item"><b>Menu</b></h4>
        <a class="w3-bar-item w3-button w3-hover-black" href="#">Link</a>
        <a class="w3-bar-item w3-button w3-hover-black" href="#">Link</a>
        <a class="w3-bar-item w3-button w3-hover-black" href="#">Link</a>
        <a class="w3-bar-item w3-button w3-hover-black" href="#">Link</a>
    </nav> -->

    <!-- Overlay effect when opening sidebar on small screens -->
    <!-- <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu"
        id="myOverlay"></div> -->

    <!-- Main content: shift it to the right by 250 pixels when the sidebar is visible -->
    <!-- <div class="w3-main" style="margin-left:250px"> -->

    <div class="w3-row w3-padding-64">
        <div class="w3-twothird w3-container">
            <h1 class="w3-text-teal">Choose a question!</h1>
            {% if latest_question_list %}
            <ul>
                {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <p>No polls are available.</p>
            {% endif %}
        </div>
        <!-- <div class="w3-third w3-container">
                <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
                <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p>
            </div> -->
    </div>

    <!-- <div class="w3-row">
            <div class="w3-twothird w3-container">
                <h1 class="w3-text-teal">Heading</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Lorem ipsum
                    dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
                    magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
                    ea commodo consequat.</p>
            </div>
            <div class="w3-third w3-container">
                <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
                <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p>
            </div>
        </div> -->

    <!-- <div class="w3-row w3-padding-64">
            <div class="w3-twothird w3-container">
                <h1 class="w3-text-teal">Heading</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Lorem ipsum
                    dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
                    magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
                    ea commodo consequat.</p>
            </div>
            <div class="w3-third w3-container">
                <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
                <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p>
            </div>
        </div> -->

    <!-- Pagination -->
    <!-- <div class="w3-center w3-padding-32">
            <div class="w3-bar">
                <a class="w3-button w3-black" href="#">1</a>
                <a class="w3-button w3-hover-black" href="#">2</a>
                <a class="w3-button w3-hover-black" href="#">3</a>
                <a class="w3-button w3-hover-black" href="#">4</a>
                <a class="w3-button w3-hover-black" href="#">5</a>
                <a class="w3-button w3-hover-black" href="#">»</a>
            </div>
        </div> -->

    <footer id="myFooter">
        <div class="w3-bottom w3-container w3-theme-l2 w3-padding-32">
            <h4>Footer</h4>
        <div class="w3-container w3-theme-l1">
            <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
        </div>
        </div>

    </footer>

    <!-- END MAIN -->
    <!-- </div> -->
</body>

</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>